<?php

namespace App\Console\Commands;

use App\Models\Product;
use App\Models\Gtin;
use Illuminate\Console\Command;

class TasnifGtin extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tasnif:gtin';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {

        $data = [
            ['id' => '000', 'nameEn' => 'USA & Canada'],
            ['id' => '001', 'nameEn' => 'USA & Canada'],
            ['id' => '002', 'nameEn' => 'USA & Canada'],
            ['id' => '003', 'nameEn' => 'USA & Canada'],
            ['id' => '004', 'nameEn' => 'USA & Canada'],
            ['id' => '005', 'nameEn' => 'USA & Canada'],
            ['id' => '006', 'nameEn' => 'USA & Canada'],
            ['id' => '007', 'nameEn' => 'USA & Canada'],
            ['id' => '008', 'nameEn' => 'USA & Canada'],
            ['id' => '009', 'nameEn' => 'USA & Canada'],

            ['id' => '010', 'nameEn' => 'USA & Canada'],
            ['id' => '011', 'nameEn' => 'USA & Canada'],
            ['id' => '012', 'nameEn' => 'USA & Canada'],
            ['id' => '013', 'nameEn' => 'USA & Canada'],
            ['id' => '014', 'nameEn' => 'USA & Canada'],
            ['id' => '015', 'nameEn' => 'USA & Canada'],
            ['id' => '016', 'nameEn' => 'USA & Canada'],
            ['id' => '017', 'nameEn' => 'USA & Canada'],
            ['id' => '018', 'nameEn' => 'USA & Canada'],
            ['id' => '019', 'nameEn' => 'USA & Canada'],

            ['id' => '030', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '031', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '032', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '033', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '034', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '035', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '036', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '037', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '038', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],


            ['id' => '039', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],

            ['id' => '040', 'nameEn' => 'USA & Canada'],
            ['id' => '041', 'nameEn' => 'USA & Canada'],
            ['id' => '042', 'nameEn' => 'USA & Canada'],
            ['id' => '043', 'nameEn' => 'USA & Canada'],
            ['id' => '044', 'nameEn' => 'USA & Canada'],
            ['id' => '045', 'nameEn' => 'USA & Canada'],
            ['id' => '046', 'nameEn' => 'USA & Canada'],
            ['id' => '047', 'nameEn' => 'USA & Canada'],
            ['id' => '048', 'nameEn' => 'USA & Canada'],
            ['id' => '049', 'nameEn' => 'USA & Canada'],

            ['id' => '050', 'nameEn' => 'USA & Canada'],
            ['id' => '051', 'nameEn' => 'USA & Canada'],
            ['id' => '052', 'nameEn' => 'USA & Canada'],
            ['id' => '053', 'nameEn' => 'USA & Canada'],
            ['id' => '054', 'nameEn' => 'USA & Canada'],
            ['id' => '055', 'nameEn' => 'USA & Canada'],
            ['id' => '056', 'nameEn' => 'USA & Canada'],
            ['id' => '057', 'nameEn' => 'USA & Canada'],
            ['id' => '058', 'nameEn' => 'USA & Canada'],
            ['id' => '059', 'nameEn' => 'USA & Canada'],

            ['id' => '060', 'nameEn' => 'USA & Canada'],
            ['id' => '061', 'nameEn' => 'USA & Canada'],
            ['id' => '062', 'nameEn' => 'USA & Canada'],
            ['id' => '063', 'nameEn' => 'USA & Canada'],
            ['id' => '064', 'nameEn' => 'USA & Canada'],
            ['id' => '065', 'nameEn' => 'USA & Canada'],
            ['id' => '066', 'nameEn' => 'USA & Canada'],
            ['id' => '067', 'nameEn' => 'USA & Canada'],
            ['id' => '068', 'nameEn' => 'USA & Canada'],
            ['id' => '069', 'nameEn' => 'USA & Canada'],

            ['id' => '070', 'nameEn' => 'USA & Canada'],
            ['id' => '071', 'nameEn' => 'USA & Canada'],
            ['id' => '072', 'nameEn' => 'USA & Canada'],
            ['id' => '073', 'nameEn' => 'USA & Canada'],
            ['id' => '074', 'nameEn' => 'USA & Canada'],
            ['id' => '075', 'nameEn' => 'USA & Canada'],
            ['id' => '076', 'nameEn' => 'USA & Canada'],
            ['id' => '077', 'nameEn' => 'USA & Canada'],
            ['id' => '078', 'nameEn' => 'USA & Canada'],
            ['id' => '079', 'nameEn' => 'USA & Canada'],

            ['id' => '080', 'nameEn' => 'USA & Canada'],
            ['id' => '081', 'nameEn' => 'USA & Canada'],
            ['id' => '082', 'nameEn' => 'USA & Canada'],
            ['id' => '083', 'nameEn' => 'USA & Canada'],
            ['id' => '084', 'nameEn' => 'USA & Canada'],
            ['id' => '085', 'nameEn' => 'USA & Canada'],
            ['id' => '086', 'nameEn' => 'USA & Canada'],
            ['id' => '087', 'nameEn' => 'USA & Canada'],
            ['id' => '088', 'nameEn' => 'USA & Canada'],
            ['id' => '089', 'nameEn' => 'USA & Canada'],

            ['id' => '090', 'nameEn' => 'USA & Canada'],
            ['id' => '091', 'nameEn' => 'USA & Canada'],
            ['id' => '092', 'nameEn' => 'USA & Canada'],
            ['id' => '093', 'nameEn' => 'USA & Canada'],
            ['id' => '094', 'nameEn' => 'USA & Canada'],
            ['id' => '095', 'nameEn' => 'USA & Canada'],
            ['id' => '096', 'nameEn' => 'USA & Canada'],
            ['id' => '097', 'nameEn' => 'USA & Canada'],
            ['id' => '098', 'nameEn' => 'USA & Canada'],
            ['id' => '099', 'nameEn' => 'USA & Canada'],

            ['id' => '100', 'nameEn' => 'USA & Canada'],
            ['id' => '101', 'nameEn' => 'USA & Canada'],
            ['id' => '102', 'nameEn' => 'USA & Canada'],
            ['id' => '103', 'nameEn' => 'USA & Canada'],
            ['id' => '104', 'nameEn' => 'USA & Canada'],
            ['id' => '105', 'nameEn' => 'USA & Canada'],
            ['id' => '106', 'nameEn' => 'USA & Canada'],
            ['id' => '107', 'nameEn' => 'USA & Canada'],
            ['id' => '108', 'nameEn' => 'USA & Canada'],
            ['id' => '109', 'nameEn' => 'USA & Canada'],

            ['id' => '110', 'nameEn' => 'USA & Canada'],
            ['id' => '111', 'nameEn' => 'USA & Canada'],
            ['id' => '112', 'nameEn' => 'USA & Canada'],
            ['id' => '113', 'nameEn' => 'USA & Canada'],
            ['id' => '114', 'nameEn' => 'USA & Canada'],
            ['id' => '115', 'nameEn' => 'USA & Canada'],
            ['id' => '116', 'nameEn' => 'USA & Canada'],
            ['id' => '117', 'nameEn' => 'USA & Canada'],
            ['id' => '118', 'nameEn' => 'USA & Canada'],
            ['id' => '119', 'nameEn' => 'USA & Canada'],

            ['id' => '120', 'nameEn' => 'USA & Canada'],
            ['id' => '121', 'nameEn' => 'USA & Canada'],
            ['id' => '122', 'nameEn' => 'USA & Canada'],
            ['id' => '123', 'nameEn' => 'USA & Canada'],
            ['id' => '124', 'nameEn' => 'USA & Canada'],
            ['id' => '125', 'nameEn' => 'USA & Canada'],
            ['id' => '126', 'nameEn' => 'USA & Canada'],
            ['id' => '127', 'nameEn' => 'USA & Canada'],
            ['id' => '128', 'nameEn' => 'USA & Canada'],
            ['id' => '129', 'nameEn' => 'USA & Canada'],

            ['id' => '130', 'nameEn' => 'USA & Canada'],
            ['id' => '131', 'nameEn' => 'USA & Canada'],
            ['id' => '132', 'nameEn' => 'USA & Canada'],
            ['id' => '133', 'nameEn' => 'USA & Canada'],
            ['id' => '134', 'nameEn' => 'USA & Canada'],
            ['id' => '135', 'nameEn' => 'USA & Canada'],
            ['id' => '136', 'nameEn' => 'USA & Canada'],
            ['id' => '137', 'nameEn' => 'USA & Canada'],
            ['id' => '138', 'nameEn' => 'USA & Canada'],




            ['id' => '139', 'nameEn' => 'USA & Canada'],

            ['id' => '150', 'nameEn' => 'USA & Canada'],
            ['id' => '151', 'nameEn' => 'USA & Canada'],
            ['id' => '152', 'nameEn' => 'USA & Canada'],
            ['id' => '153', 'nameEn' => 'USA & Canada'],
            ['id' => '154', 'nameEn' => 'USA & Canada'],
            ['id' => '155', 'nameEn' => 'USA & Canada'],
            ['id' => '156', 'nameEn' => 'USA & Canada'],
            ['id' => '157', 'nameEn' => 'USA & Canada'],
            ['id' => '158', 'nameEn' => 'USA & Canada'],
            ['id' => '159', 'nameEn' => 'USA & Canada'],


            ['id' => '240', 'nameEn' => 'Vatican City State'],
            ['id' => '241', 'nameEn' => 'Vatican City State'],
            ['id' => '242', 'nameEn' => 'Vatican City State'],
            ['id' => '243', 'nameEn' => 'Vatican City State'],
            ['id' => '244', 'nameEn' => 'Vatican City State'],
            ['id' => '245', 'nameEn' => 'Vatican City State'],
            ['id' => '246', 'nameEn' => 'Vatican City State'],
            ['id' => '247', 'nameEn' => 'Vatican City State'],
            ['id' => '248', 'nameEn' => 'Vatican City State'],
            ['id' => '249', 'nameEn' => 'Vatican City State'],


            ['id' => '250', 'nameEn' => 'Cuba'],
            ['id' => '251', 'nameEn' => 'Cuba'],
            ['id' => '252', 'nameEn' => 'Cuba'],
            ['id' => '253', 'nameEn' => 'Cuba'],
            ['id' => '254', 'nameEn' => 'Cuba'],
            ['id' => '255', 'nameEn' => 'Cuba'],
            ['id' => '256', 'nameEn' => 'Cuba'],
            ['id' => '257', 'nameEn' => 'Cuba'],
            ['id' => '258', 'nameEn' => 'Cuba'],
            ['id' => '259', 'nameEn' => 'Cuba'],

            ['id' => '260', 'nameEn' => 'Romania'],
            ['id' => '261', 'nameEn' => 'Romania'],
            ['id' => '262', 'nameEn' => 'Romania'],
            ['id' => '263', 'nameEn' => 'Romania'],
            ['id' => '264', 'nameEn' => 'Romania'],
            ['id' => '265', 'nameEn' => 'Romania'],
            ['id' => '266', 'nameEn' => 'Romania'],
            ['id' => '267', 'nameEn' => 'Romania'],
            ['id' => '268', 'nameEn' => 'Romania'],
            ['id' => '269', 'nameEn' => 'Romania'],

            ['id' => '270', 'nameEn' => 'Slovenia'],
            ['id' => '271', 'nameEn' => 'Slovenia'],
            ['id' => '272', 'nameEn' => 'Slovenia'],
            ['id' => '273', 'nameEn' => 'Slovenia'],
            ['id' => '274', 'nameEn' => 'Slovenia'],
            ['id' => '275', 'nameEn' => 'Slovenia'],
            ['id' => '276', 'nameEn' => 'Slovenia'],
            ['id' => '277', 'nameEn' => 'Slovenia'],
            ['id' => '278', 'nameEn' => 'Slovenia'],
            ['id' => '279', 'nameEn' => 'Slovenia'],

            ['id' => '280', 'nameEn' => null],
            ['id' => '281', 'nameEn' => null],
            ['id' => '282', 'nameEn' => null],
            ['id' => '283', 'nameEn' => null],
            ['id' => '284', 'nameEn' => null],
            ['id' => '285', 'nameEn' => null],
            ['id' => '286', 'nameEn' => null],
            ['id' => '287', 'nameEn' => null],
            ['id' => '288', 'nameEn' => null],
            ['id' => '289', 'nameEn' => null],



            ['id' => '300', 'nameEn' => 'France'],
            ['id' => '301', 'nameEn' => 'France'],
            ['id' => '302', 'nameEn' => 'France'],
            ['id' => '303', 'nameEn' => 'France'],
            ['id' => '304', 'nameEn' => 'France'],
            ['id' => '305', 'nameEn' => 'France'],
            ['id' => '306', 'nameEn' => 'France'],
            ['id' => '307', 'nameEn' => 'France'],
            ['id' => '308', 'nameEn' => 'France'],
            ['id' => '309', 'nameEn' => 'France'],
            ['id' => '310', 'nameEn' => 'France'],
            ['id' => '311', 'nameEn' => 'France'],
            ['id' => '312', 'nameEn' => 'France'],
            ['id' => '313', 'nameEn' => 'France'],
            ['id' => '314', 'nameEn' => 'France'],
            ['id' => '315', 'nameEn' => 'France'],
            ['id' => '316', 'nameEn' => 'France'],
            ['id' => '317', 'nameEn' => 'France'],
            ['id' => '318', 'nameEn' => 'France'],
            ['id' => '319', 'nameEn' => 'France'],

            ['id' => '320', 'nameEn' => 'France'],
            ['id' => '321', 'nameEn' => 'France'],
            ['id' => '322', 'nameEn' => 'France'],
            ['id' => '323', 'nameEn' => 'France'],
            ['id' => '324', 'nameEn' => 'France'],
            ['id' => '325', 'nameEn' => 'France'],
            ['id' => '326', 'nameEn' => 'France'],
            ['id' => '327', 'nameEn' => 'France'],
            ['id' => '328', 'nameEn' => 'France'],
            ['id' => '329', 'nameEn' => 'France'],

            ['id' => '330', 'nameEn' => 'France'],
            ['id' => '331', 'nameEn' => 'France'],
            ['id' => '332', 'nameEn' => 'France'],
            ['id' => '333', 'nameEn' => 'France'],
            ['id' => '334', 'nameEn' => 'France'],
            ['id' => '335', 'nameEn' => 'France'],
            ['id' => '336', 'nameEn' => 'France'],
            ['id' => '337', 'nameEn' => 'France'],
            ['id' => '338', 'nameEn' => 'France'],
            ['id' => '339', 'nameEn' => 'France'],

            ['id' => '340', 'nameEn' => 'Greece'],
            ['id' => '341', 'nameEn' => 'Greece'],
            ['id' => '342', 'nameEn' => 'Greece'],
            ['id' => '343', 'nameEn' => 'Greece'],
            ['id' => '344', 'nameEn' => 'Greece'],
            ['id' => '345', 'nameEn' => 'Greece'],
            ['id' => '346', 'nameEn' => 'Greece'],
            ['id' => '347', 'nameEn' => 'Greece'],
            ['id' => '348', 'nameEn' => 'Greece'],
            ['id' => '349', 'nameEn' => 'Greece'],

            ['id' => '350', 'nameEn' => 'Greece'],
            ['id' => '351', 'nameEn' => 'Greece'],
            ['id' => '352', 'nameEn' => 'Greece'],
            ['id' => '353', 'nameEn' => 'Greece'],
            ['id' => '354', 'nameEn' => 'Greece'],
            ['id' => '355', 'nameEn' => 'Greece'],
            ['id' => '356', 'nameEn' => 'Greece'],
            ['id' => '357', 'nameEn' => 'Greece'],
            ['id' => '358', 'nameEn' => 'Greece'],
            ['id' => '359', 'nameEn' => 'Greece'],

            ['id' => '360', 'nameEn' => 'Bulgaria'],
            ['id' => '361', 'nameEn' => 'Bulgaria'],
            ['id' => '362', 'nameEn' => 'Bulgaria'],
            ['id' => '363', 'nameEn' => 'Bulgaria'],
            ['id' => '364', 'nameEn' => 'Bulgaria'],
            ['id' => '365', 'nameEn' => 'Bulgaria'],
            ['id' => '366', 'nameEn' => 'Bulgaria'],
            ['id' => '367', 'nameEn' => 'Bulgaria'],
            ['id' => '368', 'nameEn' => 'Bulgaria'],
            ['id' => '369', 'nameEn' => 'Bulgaria'],

            ['id' => '370', 'nameEn' => 'Bulgaria'],
            ['id' => '371', 'nameEn' => 'Bulgaria'],
            ['id' => '372', 'nameEn' => 'Bulgaria'],
            ['id' => '373', 'nameEn' => 'Bulgaria'],
            ['id' => '374', 'nameEn' => 'Bulgaria'],
            ['id' => '375', 'nameEn' => 'Bulgaria'],
            ['id' => '376', 'nameEn' => 'Bulgaria'],
            ['id' => '377', 'nameEn' => 'Bulgaria'],
            ['id' => '378', 'nameEn' => 'Bulgaria'],
            ['id' => '379', 'nameEn' => 'Bulgaria'],



            ['id' => '380', 'nameEn' => 'Bulgaria'],
            ['id' => '381', 'nameEn' => 'Bulgaria'],
            ['id' => '382', 'nameEn' => 'Bulgaria'],
            ['id' => '383', 'nameEn' => 'Bulgaria'],
            ['id' => '384', 'nameEn' => 'Bulgaria'],
            ['id' => '385', 'nameEn' => 'Bulgaria'],
            ['id' => '386', 'nameEn' => 'Bulgaria'],
            ['id' => '387', 'nameEn' => 'Bulgaria'],
            ['id' => '388', 'nameEn' => 'Bulgaria'],
            ['id' => '389', 'nameEn' => 'Bulgaria'],

            ['id' => '400', 'nameEn' => 'Germany'],
            ['id' => '401', 'nameEn' => 'Germany'],
            ['id' => '402', 'nameEn' => 'Germany'],
            ['id' => '403', 'nameEn' => 'Germany'],
            ['id' => '404', 'nameEn' => 'Germany'],
            ['id' => '405', 'nameEn' => 'Germany'],
            ['id' => '406', 'nameEn' => 'Germany'],
            ['id' => '407', 'nameEn' => 'Germany'],
            ['id' => '408', 'nameEn' => 'Germany'],
            ['id' => '409', 'nameEn' => 'Germany'],

            ['id' => '410', 'nameEn' => 'Germany'],
            ['id' => '411', 'nameEn' => 'Germany'],
            ['id' => '412', 'nameEn' => 'Germany'],
            ['id' => '413', 'nameEn' => 'Germany'],
            ['id' => '414', 'nameEn' => 'Germany'],
            ['id' => '415', 'nameEn' => 'Germany'],
            ['id' => '416', 'nameEn' => 'Germany'],
            ['id' => '417', 'nameEn' => 'Germany'],
            ['id' => '418', 'nameEn' => 'Germany'],
            ['id' => '419', 'nameEn' => 'Germany'],
            ['id' => '420', 'nameEn' => 'Germany'],
            ['id' => '421', 'nameEn' => 'Germany'],
            ['id' => '422', 'nameEn' => 'Germany'],
            ['id' => '423', 'nameEn' => 'Germany'],
            ['id' => '424', 'nameEn' => 'Germany'],
            ['id' => '425', 'nameEn' => 'Germany'],
            ['id' => '426', 'nameEn' => 'Germany'],
            ['id' => '427', 'nameEn' => 'Germany'],
            ['id' => '428', 'nameEn' => 'Germany'],
            ['id' => '429', 'nameEn' => 'Germany'],
            ['id' => '429', 'nameEn' => 'Germany'],

            ['id' => '430', 'nameEn' => 'Germany'],
            ['id' => '431', 'nameEn' => 'Germany'],
            ['id' => '432', 'nameEn' => 'Germany'],
            ['id' => '433', 'nameEn' => 'Germany'],
            ['id' => '434', 'nameEn' => 'Germany'],
            ['id' => '435', 'nameEn' => 'Germany'],
            ['id' => '436', 'nameEn' => 'Germany'],
            ['id' => '437', 'nameEn' => 'Germany'],
            ['id' => '438', 'nameEn' => 'Germany'],
            ['id' => '439', 'nameEn' => 'Germany'],

            ['id' => '440', 'nameEn' => 'Germany'],

            ['id' => '441', 'nameEn' => 'Germany'],
            ['id' => '442', 'nameEn' => 'Germany'],
            ['id' => '443', 'nameEn' => 'Germany'],
            ['id' => '444', 'nameEn' => 'Germany'],
            ['id' => '445', 'nameEn' => 'Germany'],
            ['id' => '446', 'nameEn' => 'Germany'],
            ['id' => '447', 'nameEn' => 'Germany'],
            ['id' => '448', 'nameEn' => 'Germany'],
            ['id' => '449', 'nameEn' => 'Germany'],



            ['id' => '450', 'nameEn' => 'Japan'],
            ['id' => '451', 'nameEn' => 'Japan'],
            ['id' => '452', 'nameEn' => 'Japan'],
            ['id' => '453', 'nameEn' => 'Japan'],
            ['id' => '454', 'nameEn' => 'Japan'],
            ['id' => '455', 'nameEn' => 'Japan'],
            ['id' => '456', 'nameEn' => 'Japan'],
            ['id' => '457', 'nameEn' => 'Japan'],
            ['id' => '458', 'nameEn' => 'Japan'],
            ['id' => '459', 'nameEn' => 'Japan'],
            ['id' => '460', 'nameEn' => 'Russia'],
            ['id' => '461', 'nameEn' => 'Russia'],
            ['id' => '462', 'nameEn' => 'Russia'],
            ['id' => '463', 'nameEn' => 'Russia'],
            ['id' => '464', 'nameEn' => 'Russia'],
            ['id' => '465', 'nameEn' => 'Russia'],
            ['id' => '466', 'nameEn' => 'Russia'],
            ['id' => '467', 'nameEn' => 'Russia'],
            ['id' => '468', 'nameEn' => 'Russia'],
            // ...
            ['id' => '469', 'nameEn' => 'Russia'],

            ['id' => '470', 'nameEn' => 'Kyrgyzstan'],
            ['id' => '471', 'nameEn' => 'Taiwan'],
            ['id' => '474', 'nameEn' => 'Estonia'],
            ['id' => '475', 'nameEn' => 'Latvia'],
            ['id' => '476', 'nameEn' => 'Azerbaijan'],
            ['id' => '477', 'nameEn' => 'Lithuania'],
            ['id' => '478', 'nameEn' => 'Uzbekistan'],
            ['id' => '479', 'nameEn' => 'Sri Lanka'],
            ['id' => '480', 'nameEn' => 'Philippines'],
            ['id' => '481', 'nameEn' => 'Belarus'],
            ['id' => '482', 'nameEn' => 'Ukraine'],
            ['id' => '483', 'nameEn' => 'Turkmenistan'],
            ['id' => '484', 'nameEn' => 'Moldova'],
            ['id' => '485', 'nameEn' => 'Armenia'],
            ['id' => '486', 'nameEn' => 'Georgia'],
            ['id' => '487', 'nameEn' => 'Kazakhstan'],
            ['id' => '488', 'nameEn' => 'Tajikistan'],
            ['id' => '489', 'nameEn' => 'Hong Kong'],
            ['id' => '490', 'nameEn' => 'Japan'],
            ['id' => '491', 'nameEn' => 'Japan'],
            ['id' => '492', 'nameEn' => 'Japan'],
            ['id' => '493', 'nameEn' => 'Japan'],
            ['id' => '494', 'nameEn' => 'Japan'],
            ['id' => '495', 'nameEn' => 'Japan'],
            ['id' => '496', 'nameEn' => 'Japan'],
            ['id' => '497', 'nameEn' => 'Japan'],
            ['id' => '498', 'nameEn' => 'Japan'],
            ['id' => '499', 'nameEn' => 'Japan'],

            ['id' => '500', 'nameEn' => 'UK'],
            ['id' => '501', 'nameEn' => 'UK'],
            ['id' => '502', 'nameEn' => 'UK'],
            ['id' => '503', 'nameEn' => 'UK'],
            ['id' => '504', 'nameEn' => 'UK'],
            ['id' => '505', 'nameEn' => 'UK'],
            ['id' => '506', 'nameEn' => 'UK'],
            ['id' => '507', 'nameEn' => 'UK'],
            ['id' => '508', 'nameEn' => 'UK'],
            ['id' => '509', 'nameEn' => 'UK'],
            ['id' => '520', 'nameEn' => 'Greece'],
            ['id' => '521', 'nameEn' => 'Greece'],
            ['id' => '522', 'nameEn' => 'Greece'],
            ['id' => '523', 'nameEn' => 'Greece'],
            ['id' => '524', 'nameEn' => 'Greece'],
            ['id' => '525', 'nameEn' => 'Greece'],
            ['id' => '526', 'nameEn' => 'Greece'],
            ['id' => '527', 'nameEn' => 'Greece'],
            ['id' => '528', 'nameEn' => 'Greece'],
            ['id' => '529', 'nameEn' => 'Greece'],

            ['id' => '530', 'nameEn' => 'Albania'],
            ['id' => '531', 'nameEn' => 'Macedonia'],
            ['id' => '532', 'nameEn' => 'Malta'],
            ['id' => '533', 'nameEn' => 'Cyprus'],
            ['id' => '534', 'nameEn' => 'Malta'],
            ['id' => '535', 'nameEn' => 'Malta'],
            ['id' => '536', 'nameEn' => 'Malta'],
            ['id' => '537', 'nameEn' => 'Malta'],
            ['id' => '538', 'nameEn' => 'Malta'],
            ['id' => '539', 'nameEn' => 'Malta'],

            ['id' => '540',  'nameEn' => 'Portugal'],
            ['id' => '541',  'nameEn' => 'Portugal'],
            ['id' => '542',  'nameEn' => 'Portugal'],
            ['id' => '543',  'nameEn' => 'Portugal'],
            ['id' => '544',  'nameEn' => 'Portugal'],
            ['id' => '545',  'nameEn' => 'Portugal'],
            ['id' => '546',  'nameEn' => 'Portugal'],
            ['id' => '547',  'nameEn' => 'Portugal'],
            ['id' => '548',  'nameEn' => 'Portugal'],
            ['id' => '549',  'nameEn' => 'Portugal'],
            ['id' => '550',  'nameEn' => 'Portugal'],
            ['id' => '551',  'nameEn' => 'Portugal'],
            ['id' => '552',  'nameEn' => 'Portugal'],
            ['id' => '553',  'nameEn' => 'Portugal'],
            ['id' => '554',  'nameEn' => 'Portugal'],
            ['id' => '555',  'nameEn' => 'Portugal'],
            ['id' => '556',  'nameEn' => 'Portugal'],
            ['id' => '557',  'nameEn' => 'Portugal'],
            ['id' => '558',  'nameEn' => 'Portugal'],
            ['id' => '559',  'nameEn' => 'Portugal'],


            ['id' => '560',  'nameEn' => 'Portugal'],
            ['id' => '561',  'nameEn' => 'Portugal'],
            ['id' => '562',  'nameEn' => 'Portugal'],
            ['id' => '563',  'nameEn' => 'Portugal'],
            ['id' => '564',  'nameEn' => 'Portugal'],
            ['id' => '565',  'nameEn' => 'Portugal'],
            ['id' => '566',  'nameEn' => 'Portugal'],
            ['id' => '567',  'nameEn' => 'Portugal'],
            ['id' => '568',  'nameEn' => 'Portugal'],
            ['id' => '569',  'nameEn' => 'Portugal'],
            ['id' => '570', 'nameEn' => 'Denmark'],
            ['id' => '571', 'nameEn' => 'Denmark'],
            ['id' => '572', 'nameEn' => 'Denmark'],
            ['id' => '573', 'nameEn' => 'Denmark'],
            ['id' => '574', 'nameEn' => 'Denmark'],
            ['id' => '575', 'nameEn' => 'Denmark'],
            ['id' => '576', 'nameEn' => 'Denmark'],
            ['id' => '577', 'nameEn' => 'Denmark'],
            ['id' => '578', 'nameEn' => 'Denmark'],
            ['id' => '579', 'nameEn' => 'Denmark'],

            ['id' => '580',  'nameEn' => 'Poland'],
            ['id' => '581',  'nameEn' => 'Poland'],
            ['id' => '582',  'nameEn' => 'Poland'],
            ['id' => '583',  'nameEn' => 'Poland'],
            ['id' => '584',  'nameEn' => 'Poland'],
            ['id' => '585',  'nameEn' => 'Poland'],
            ['id' => '586',  'nameEn' => 'Poland'],
            ['id' => '587',  'nameEn' => 'Poland'],
            ['id' => '588',  'nameEn' => 'Poland'],
            ['id' => '589',  'nameEn' => 'Poland'],


            ['id' => '590', 'nameEn' => 'Poland'],
            ['id' => '591', 'nameEn' => 'Poland'],
            ['id' => '592', 'nameEn' => 'Poland'],
            ['id' => '593', 'nameEn' => 'Poland'],
            ['id' => '594', 'nameEn' => 'Poland'],
            ['id' => '595', 'nameEn' => 'Poland'],
            ['id' => '596', 'nameEn' => 'Poland'],
            ['id' => '597', 'nameEn' => 'Poland'],
            ['id' => '598', 'nameEn' => 'Poland'],
            ['id' => '599', 'nameEn' => 'Poland'],

            ['id' => '600', 'nameEn' => 'South Africa'],
            ['id' => '601', 'nameEn' => 'South Africa'],
            ['id' => '602', 'nameEn' => 'South Africa'],
            ['id' => '603', 'nameEn' => 'South Africa'],
            ['id' => '604', 'nameEn' => 'South Africa'],
            ['id' => '605', 'nameEn' => 'South Africa'],
            ['id' => '606', 'nameEn' => 'South Africa'],
            ['id' => '607', 'nameEn' => 'South Africa'],
            ['id' => '608', 'nameEn' => 'South Africa'],
            ['id' => '609', 'nameEn' => 'South Africa'],

            ['id' => '610',  'nameEn' => 'Morocco'],
            ['id' => '611',  'nameEn' => 'Morocco'],
            ['id' => '612',  'nameEn' => 'Morocco'],
            ['id' => '613',  'nameEn' => 'Morocco'],
            ['id' => '614',  'nameEn' => 'Morocco'],
            ['id' => '615',  'nameEn' => 'Morocco'],
            ['id' => '616',  'nameEn' => 'Morocco'],
            ['id' => '617',  'nameEn' => 'Morocco'],
            ['id' => '618',  'nameEn' => 'Morocco'],
            ['id' => '619',  'nameEn' => 'Morocco'],
            ['id' => '620', 'nameEn' => 'Tanzania'],
            ['id' => '621', 'nameEn' => 'Syria'],
            ['id' => '622', 'nameEn' => 'Egypt'],
            ['id' => '623', 'nameEn' => 'Egypt'],
            ['id' => '624', 'nameEn' => 'Libya'],
            ['id' => '625', 'nameEn' => 'Egypt'],
            ['id' => '626', 'nameEn' => 'Egypt'],
            ['id' => '627', 'nameEn' => 'Egypt'],
            ['id' => '628', 'nameEn' => 'Egypt'],
            ['id' => '629', 'nameEn' => 'Egypt'],
            ['id' => '623', 'nameEn' => 'Tunisia'],
            ['id' => '624', 'nameEn' => 'Tunisia'],
            ['id' => '625', 'nameEn' => 'Tunisia'],
            ['id' => '626', 'nameEn' => 'Tunisia'],
            ['id' => '627', 'nameEn' => 'Tunisia'],
            ['id' => '628', 'nameEn' => 'Tunisia'],
            ['id' => '629', 'nameEn' => 'Tunisia'],





            ['id' => '630', 'nameEn' => 'Egypt'],
            ['id' => '631', 'nameEn' => 'Egypt'],
            ['id' => '632', 'nameEn' => 'Egypt'],
            ['id' => '633', 'nameEn' => 'Egypt'],
            ['id' => '634', 'nameEn' => 'Egypt'],
            ['id' => '635', 'nameEn' => 'Egypt'],
            ['id' => '636', 'nameEn' => 'Egypt'],
            ['id' => '637', 'nameEn' => 'Egypt'],
            ['id' => '638', 'nameEn' => 'Egypt'],
            ['id' => '639', 'nameEn' => 'Egypt'],

            ['id' => '640',  'nameEn' => 'Finland'],
            ['id' => '641',  'nameEn' => 'Finland'],
            ['id' => '642',  'nameEn' => 'Finland'],
            ['id' => '643',  'nameEn' => 'Finland'],
            ['id' => '644',  'nameEn' => 'Finland'],
            ['id' => '645',  'nameEn' => 'Finland'],
            ['id' => '646',  'nameEn' => 'Finland'],
            ['id' => '647',  'nameEn' => 'Finland'],
            ['id' => '648',  'nameEn' => 'Finland'],
            ['id' => '649',  'nameEn' => 'Finland'],


            ['id' => '650',  'nameEn' => 'Finland'],
            ['id' => '651',  'nameEn' => 'Finland'],
            ['id' => '652',  'nameEn' => 'Finland'],
            ['id' => '653',  'nameEn' => 'Finland'],
            ['id' => '654',  'nameEn' => 'Finland'],
            ['id' => '655',  'nameEn' => 'Finland'],
            ['id' => '656',  'nameEn' => 'Finland'],
            ['id' => '657',  'nameEn' => 'Finland'],
            ['id' => '658',  'nameEn' => 'Finland'],
            ['id' => '659',  'nameEn' => 'Finland'],

            ['id' => '660', 'nameEn' => null],
            ['id' => '661', 'nameEn' => null],
            ['id' => '690', 'nameEn' => 'China'],
            ['id' => '691', 'nameEn' => 'China'],
            ['id' => '692', 'nameEn' => 'China'],
            ['id' => '693', 'nameEn' => 'China'],
            ['id' => '694', 'nameEn' => 'China'],
            ['id' => '695', 'nameEn' => 'China'],
            ['id' => '696', 'nameEn' => 'China'],
            ['id' => '697', 'nameEn' => 'China'],
            ['id' => '698', 'nameEn' => 'China'],

            ['id' => '699', 'nameEn' => 'China'],
            ['id' => '700', 'nameEn' => 'Norway'],
            ['id' => '701', 'nameEn' => 'Norway'],
            ['id' => '702', 'nameEn' => 'Norway'],
            ['id' => '703', 'nameEn' => 'Norway'],
            ['id' => '704', 'nameEn' => 'Norway'],
            ['id' => '705', 'nameEn' => 'Norway'],
            ['id' => '706', 'nameEn' => 'Norway'],
            ['id' => '707', 'nameEn' => 'Norway'],
            ['id' => '708', 'nameEn' => 'Norway'],
            ['id' => '709', 'nameEn' => 'Norway'],

            ['id' => '710', 'nameEn' => 'Colombia'],
            ['id' => '711', 'nameEn' => 'Colombia'],
            ['id' => '712', 'nameEn' => 'Colombia'],
            ['id' => '713', 'nameEn' => 'Colombia'],
            ['id' => '714', 'nameEn' => 'Colombia'],
            ['id' => '715', 'nameEn' => 'Colombia'],
            ['id' => '716', 'nameEn' => 'Colombia'],
            ['id' => '717', 'nameEn' => 'Colombia'],
            ['id' => '718', 'nameEn' => 'Colombia'],
            ['id' => '719', 'nameEn' => 'Colombia'],

            ['id' => '720', 'nameEn' => 'Argentina'],
            ['id' => '721', 'nameEn' => 'Argentina'],
            ['id' => '722', 'nameEn' => 'Argentina'],
            ['id' => '723', 'nameEn' => 'Argentina'],
            ['id' => '724', 'nameEn' => 'Argentina'],
            ['id' => '725', 'nameEn' => 'Argentina'],
            ['id' => '726', 'nameEn' => 'Argentina'],
            ['id' => '727', 'nameEn' => 'Argentina'],
            ['id' => '728', 'nameEn' => 'Argentina'],




            ['id' => '729', 'nameEn' => 'Israel'],
            ['id' => '730', 'nameEn' => 'Chile'],
            ['id' => '731', 'nameEn' => 'Chile'],
            ['id' => '732', 'nameEn' => 'Chile'],
            ['id' => '733', 'nameEn' => 'Chile'],
            ['id' => '734', 'nameEn' => 'Chile'],
            ['id' => '735', 'nameEn' => 'Chile'],
            ['id' => '736', 'nameEn' => 'Chile'],
            ['id' => '737', 'nameEn' => 'Chile'],
            ['id' => '738', 'nameEn' => 'Chile'],
            ['id' => '739', 'nameEn' => 'Chile'],

            ['id' => '740', 'nameEn' => 'Guatemala'],
            ['id' => '741', 'nameEn' => 'El Salvador'],
            ['id' => '742', 'nameEn' => 'Honduras'],
            ['id' => '743', 'nameEn' => 'Nicaragua'],
            ['id' => '744', 'nameEn' => 'Costa Rica'],
            ['id' => '745', 'nameEn' => 'Panama'],
            ['id' => '746', 'nameEn' => 'Dominican Republic'],
            ['id' => '747', 'nameEn' => 'Dominican Republic'],
            ['id' => '748', 'nameEn' => 'Dominican Republic'],
            ['id' => '749', 'nameEn' => 'Dominican Republic'],


            ['id' => '750', 'nameEn' => 'Mexico'],
            ['id' => '751', 'nameEn' => 'Mexico'],
            ['id' => '752', 'nameEn' => 'Mexico'],
            ['id' => '753', 'nameEn' => 'Mexico'],
            ['id' => '754', 'nameEn' => 'Mexico'],
            ['id' => '755', 'nameEn' => 'Mexico'],
            ['id' => '756', 'nameEn' => 'Mexico'],
            ['id' => '757', 'nameEn' => 'Mexico'],
            ['id' => '758', 'nameEn' => 'Mexico'],
            ['id' => '759', 'nameEn' => 'Mexico'],

            ['id' => '760',  'nameEn' => 'Switzerland'],
            ['id' => '761',  'nameEn' => 'Switzerland'],
            ['id' => '762',  'nameEn' => 'Switzerland'],
            ['id' => '763',  'nameEn' => 'Switzerland'],
            ['id' => '764',  'nameEn' => 'Switzerland'],
            ['id' => '765',  'nameEn' => 'Switzerland'],
            ['id' => '766',  'nameEn' => 'Switzerland'],
            ['id' => '767',  'nameEn' => 'Switzerland'],
            ['id' => '768',  'nameEn' => 'Switzerland'],
            ['id' => '769',  'nameEn' => 'Switzerland'],

            ['id' => '770',  'nameEn' => 'Colombia'],
            ['id' => '771',  'nameEn' => 'Colombia'],
            ['id' => '772',  'nameEn' => 'Colombia'],
            ['id' => '773',  'nameEn' => 'Colombia'],
            ['id' => '774',  'nameEn' => 'Colombia'],
            ['id' => '775',  'nameEn' => 'Colombia'],
            ['id' => '776',  'nameEn' => 'Colombia'],
            ['id' => '777',  'nameEn' => 'Colombia'],
            ['id' => '778',  'nameEn' => 'Colombia'],
            ['id' => '779',  'nameEn' => 'Colombia'],


            ['id' => '780',  'nameEn' => 'Colombia'],
            ['id' => '781',  'nameEn' => 'Colombia'],
            ['id' => '782',  'nameEn' => 'Colombia'],
            ['id' => '783',  'nameEn' => 'Colombia'],
            ['id' => '784',  'nameEn' => 'Colombia'],
            ['id' => '785',  'nameEn' => 'Colombia'],
            ['id' => '786',  'nameEn' => 'Colombia'],
            ['id' => '787',  'nameEn' => 'Puerto Rico'],
            ['id' => '788',  'nameEn' => 'Puerto Rico'],

            ['id' => '789', 'nameEn' => 'Brazil'],
            ['id' => '790', 'nameEn' => 'Brazil'],
            ['id' => '791', 'nameEn' => 'Brazil'],
            ['id' => '792', 'nameEn' => 'Brazil'],
            ['id' => '793', 'nameEn' => 'Brazil'],
            ['id' => '794', 'nameEn' => 'Brazil'],
            ['id' => '795', 'nameEn' => 'Brazil'],
            ['id' => '796', 'nameEn' => 'Brazil'],
            ['id' => '797', 'nameEn' => 'Brazil'],
            ['id' => '798', 'nameEn' => 'Brazil'],


            ['id' => '800', 'nameEn' => 'Italy'],
            ['id' => '801', 'nameEn' => 'Italy'],
            ['id' => '802', 'nameEn' => 'Italy'],
            ['id' => '803', 'nameEn' => 'Italy'],
            ['id' => '804', 'nameEn' => 'Italy'],
            ['id' => '805', 'nameEn' => 'Italy'],
            ['id' => '806', 'nameEn' => 'Italy'],
            ['id' => '807', 'nameEn' => 'Italy'],
            ['id' => '808', 'nameEn' => 'Italy'],
            ['id' => '809', 'nameEn' => 'Italy'],

            ['id' => '810', 'nameEn' => 'Italy'],
            ['id' => '811', 'nameEn' => 'Italy'],
            ['id' => '812', 'nameEn' => 'Italy'],
            ['id' => '813', 'nameEn' => 'Italy'],
            ['id' => '814', 'nameEn' => 'Italy'],
            ['id' => '815', 'nameEn' => 'Italy'],
            ['id' => '816', 'nameEn' => 'Italy'],
            ['id' => '817', 'nameEn' => 'Italy'],
            ['id' => '818', 'nameEn' => 'Italy'],
            ['id' => '819', 'nameEn' => 'Italy'],

            ['id' => '820',  'nameEn' => 'Italy'],
            ['id' => '821',  'nameEn' => 'Italy'],
            ['id' => '822',  'nameEn' => 'Italy'],
            ['id' => '823',  'nameEn' => 'Italy'],
            ['id' => '824',  'nameEn' => 'Italy'],
            ['id' => '825',  'nameEn' => 'Italy'],
            ['id' => '826',  'nameEn' => 'Italy'],
            ['id' => '827',  'nameEn' => 'Italy'],
            ['id' => '828',  'nameEn' => 'Italy'],
            ['id' => '829',  'nameEn' => 'Italy'],

            ['id' => '830', 'nameEn' => 'Italy'],
            ['id' => '831', 'nameEn' => 'Italy'],
            ['id' => '832', 'nameEn' => 'Italy'],
            ['id' => '833', 'nameEn' => 'Italy'],
            ['id' => '834', 'nameEn' => 'Italy'],
            ['id' => '835', 'nameEn' => 'Italy'],
            ['id' => '836', 'nameEn' => 'Italy'],
            ['id' => '837', 'nameEn' => 'Italy'],
            ['id' => '838', 'nameEn' => 'Italy'],
            ['id' => '839', 'nameEn' => 'Italy'],

            ['id' => '840', 'nameEn' => 'Spain'],
            ['id' => '841', 'nameEn' => 'Spain'],
            ['id' => '842', 'nameEn' => 'Spain'],
            ['id' => '843', 'nameEn' => 'Spain'],
            ['id' => '844', 'nameEn' => 'Spain'],
            ['id' => '845', 'nameEn' => 'Spain'],
            ['id' => '846', 'nameEn' => 'Spain'],
            ['id' => '847', 'nameEn' => 'Spain'],
            ['id' => '848', 'nameEn' => 'Spain'],
            // ...
            ['id' => '849', 'nameEn' => 'Spain'],
            ['id' => '850', 'nameEn' => 'Cuba'],
            ['id' => '858', 'nameEn' => 'Slovakia'],
            ['id' => '859', 'nameEn' => 'Czech Republic'],
            ['id' => '860', 'nameEn' => 'Serbia'],
            ['id' => '861', 'nameEn' => 'Mongolia'],
            ['id' => '862', 'nameEn' => 'Morocco'],
            ['id' => '863', 'nameEn' => 'Côte d\'Ivoire'],
            ['id' => '864', 'nameEn' => 'Syria'],
            ['id' => '865', 'nameEn' => 'Mongolia'],
            ['id' => '866', 'nameEn' => 'North Korea'],
            ['id' => '867', 'nameEn' => 'Bangladesh'],
            ['id' => '868', 'nameEn' => 'Türkiye'],
            ['id' => '869', 'nameEn' => 'Türkiye'],

            ['id' => '870', 'nameEn' => 'Netherlands'],
            ['id' => '871', 'nameEn' => 'Netherlands'],
            ['id' => '872', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '873', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '874', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '875', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '876', 'nameEn' => 'Saint Pierre and Miquelon'],
            ['id' => '877', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '878', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '879', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '880', 'nameEn' => 'South Korea'],
            ['id' => '881', 'nameEn' => 'South Korea'],
            ['id' => '882', 'nameEn' => 'South Korea'],
            ['id' => '883', 'nameEn' => 'South Korea'],
            ['id' => '884', 'nameEn' => 'Cambodia'],
            ['id' => '885', 'nameEn' => 'Thailand'],
            ['id' => '886', 'nameEn' => 'Taiwan'],
            ['id' => '887', 'nameEn' => 'Bangladesh'],
            ['id' => '888', 'nameEn' => 'Singapore'],
            ['id' => '889', 'nameEn' => 'Singapore'],


            ['id' => '890', 'nameEn' => 'India'],
            ['id' => '891', 'nameEn' => 'India'],
            ['id' => '892', 'nameEn' => 'India'],
            ['id' => '893', 'nameEn' => 'India'],
            ['id' => '894', 'nameEn' => 'India'],
            ['id' => '895', 'nameEn' => 'India'],
            ['id' => '896', 'nameEn' => 'India'],
            ['id' => '897', 'nameEn' => 'India'],
            ['id' => '898', 'nameEn' => 'India'],
            ['id' => '899', 'nameEn' => 'India'],

            ['id' => '900', 'nameEn' => 'Austria'],
            ['id' => '901', 'nameEn' => 'Austria'],
            ['id' => '902', 'nameEn' => 'Austria'],
            ['id' => '903', 'nameEn' => 'Austria'],
            ['id' => '904', 'nameEn' => 'Austria'],
            ['id' => '905', 'nameEn' => 'Austria'],
            ['id' => '906', 'nameEn' => 'Austria'],
            ['id' => '907', 'nameEn' => 'Austria'],
            ['id' => '908', 'nameEn' => 'Austria'],
            ['id' => '909', 'nameEn' => 'Austria'],

            ['id' => '910', 'nameEn' => 'Austria'],
            ['id' => '911', 'nameEn' => 'Austria'],
            ['id' => '912', 'nameEn' => 'Austria'],
            ['id' => '913', 'nameEn' => 'Austria'],
            ['id' => '914', 'nameEn' => 'Austria'],
            ['id' => '915', 'nameEn' => 'Austria'],
            ['id' => '916', 'nameEn' => 'Austria'],
            ['id' => '917', 'nameEn' => 'Austria'],
            ['id' => '918', 'nameEn' => 'Austria'],

            ['id' => '919', 'nameEn' => 'Austria'],

            ['id' => '920', 'nameEn' => 'Serbia'],
            ['id' => '921', 'nameEn' => 'Bosnia and Herzegovina'],
            ['id' => '922', 'nameEn' => 'Montenegro'],
            ['id' => '923', 'nameEn' => 'Slovenia'],
            ['id' => '924', 'nameEn' => 'Croatia'],
            ['id' => '925', 'nameEn' => 'Republic of North Macedonia'],
            ['id' => '926', 'nameEn' => 'Albania'],
            ['id' => '927', 'nameEn' => 'Malta'],
            ['id' => '928', 'nameEn' => null],
            ['id' => '929', 'nameEn' => null],

            ['id' => '930', 'nameEn' => 'Australia'],
            ['id' => '931', 'nameEn' => 'Australia'],
            ['id' => '932', 'nameEn' => 'Australia'],
            ['id' => '933', 'nameEn' => 'Australia'],
            ['id' => '934', 'nameEn' => 'Australia'],
            ['id' => '935', 'nameEn' => 'Australia'],
            ['id' => '936', 'nameEn' => 'Australia'],
            ['id' => '937', 'nameEn' => 'Australia'],
            ['id' => '938', 'nameEn' => 'Australia'],
            // ...
            ['id' => '939', 'nameEn' => 'Australia'],

            ['id' => '940', 'nameEn' => 'New Zealand'],
            ['id' => '941', 'nameEn' => 'New Zealand'],
            ['id' => '942', 'nameEn' => 'New Zealand'],
            ['id' => '943', 'nameEn' => 'New Zealand'],
            ['id' => '944', 'nameEn' => 'New Zealand'],
            ['id' => '945', 'nameEn' => 'New Zealand'],
            ['id' => '946', 'nameEn' => 'New Zealand'],
            ['id' => '947', 'nameEn' => 'New Zealand'],
            ['id' => '948', 'nameEn' => 'New Zealand'],
            // ...
            ['id' => '949', 'nameEn' => 'New Zealand'],

            ['id' => '950', 'nameEn' => 'Global Office Use'],
            ['id' => '951', 'nameEn' => 'Global Office Use'],
            ['id' => '952', 'nameEn' => 'Global Office Use'],
            ['id' => '953', 'nameEn' => 'Global Office Use'],
            ['id' => '954', 'nameEn' => 'Global Office Use'],


            ['id' => '955', 'nameEn' => 'Malaysia'],
            ['id' => '956', 'nameEn' => 'Malaysia'],
            ['id' => '957', 'nameEn' => 'Malaysia'],

            ['id' => '958', 'nameEn' => 'Macau'],
            ['id' => '959', 'nameEn' => 'Macau'],

            ['id' => '960', 'nameEn' => 'GS1 US'],
            ['id' => '961', 'nameEn' => 'GS1 US'],
            ['id' => '962', 'nameEn' => 'GS1 US'],
            ['id' => '963', 'nameEn' => 'GS1 US'],
            ['id' => '964', 'nameEn' => 'GS1 US'],
            ['id' => '965', 'nameEn' => 'GS1 US'],
            ['id' => '966', 'nameEn' => 'GS1 US'],
            ['id' => '967', 'nameEn' => 'GS1 US'],
            ['id' => '968', 'nameEn' => 'GS1 US'],
            ['id' => '969', 'nameEn' => 'GS1 US'],

            ['id' => '970', 'nameEn' => 'GS1 US'],
            ['id' => '971', 'nameEn' => 'GS1 US'],
            ['id' => '972', 'nameEn' => 'GS1 US'],
            ['id' => '973', 'nameEn' => 'GS1 US'],
            ['id' => '974', 'nameEn' => 'GS1 US'],
            ['id' => '975', 'nameEn' => 'Coupons'],
            ['id' => '976', 'nameEn' => 'Coupons'],
            ['id' => '977', 'nameEn' => 'Coupons'],
            ['id' => '978', 'nameEn' => 'Coupons'],
            ['id' => '979', 'nameEn' => 'Coupons'],

            ['id' => '980', 'nameEn' => 'Coupons'],
            ['id' => '981', 'nameEn' => 'Coupons'],
            ['id' => '982', 'nameEn' => 'Coupons'],
            ['id' => '983', 'nameEn' => 'Coupons'],
            ['id' => '984', 'nameEn' => 'Coupons'],
            ['id' => '985', 'nameEn' => null],
            ['id' => '986', 'nameEn' => null],
            ['id' => '987', 'nameEn' => null],
            ['id' => '988', 'nameEn' => null],
            ['id' => '989', 'nameEn' => null],
            ['id' => '990', 'nameEn' => 'Coupons'],
            ['id' => '991', 'nameEn' => 'Coupons'],
            ['id' => '992', 'nameEn' => 'Coupons'],
            ['id' => '993', 'nameEn' => 'Coupons'],
            ['id' => '994', 'nameEn' => 'Coupons'],
            ['id' => '995', 'nameEn' => 'Coupons'],
            ['id' => '996', 'nameEn' => 'Coupons'],
            ['id' => '997', 'nameEn' => 'Coupons'],
            ['id' => '998', 'nameEn' => 'Coupons'],
            ['id' => '999', 'nameEn' => 'Coupons'],
        ];

        foreach ($data as $row) {
            Gtin::updateOrCreate(['id' => $row['id']], $row);
        }
    }
}
