<?php

namespace App\Console\Commands;

use App\Models\Product;
use App\Models\Gtin;
use Illuminate\Console\Command;

class TasnifGtin extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tasnif:gtin';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {

        $data = [
            ['id' => '000', 'nameEn' => 'USA & Canada'],
            ['id' => '001', 'nameEn' => 'USA & Canada'],
            ['id' => '002', 'nameEn' => 'USA & Canada'],
            // ...
            ['id' => '019', 'nameEn' => 'USA & Canada'],

            ['id' => '030', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            ['id' => '031', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],
            // ...
            ['id' => '039', 'nameEn' => 'USA & Canada (Drugs, Coupons)'],

            ['id' => '060', 'nameEn' => 'USA & Canada'],
            // ...
            ['id' => '139', 'nameEn' => 'USA & Canada'],
            ['id' => '140', 'nameEn' => null],
            ['id' => '141', 'nameEn' => null],
            ['id' => '142', 'nameEn' => null],
            ['id' => '143', 'nameEn' => null],
            ['id' => '144', 'nameEn' => null],
            ['id' => '145', 'nameEn' => null],
            ['id' => '146', 'nameEn' => null],
            ['id' => '147', 'nameEn' => null],
            ['id' => '148', 'nameEn' => null],
            ['id' => '149', 'nameEn' => null],
            ['id' => '150', 'nameEn' => 'USA & Canada'],
            ['id' => '151', 'nameEn' => 'USA & Canada'],
            ['id' => '152', 'nameEn' => 'USA & Canada'],
            ['id' => '153', 'nameEn' => 'USA & Canada'],
            ['id' => '154', 'nameEn' => 'USA & Canada'],
            ['id' => '155', 'nameEn' => 'USA & Canada'],
            ['id' => '156', 'nameEn' => 'USA & Canada'],
            ['id' => '157', 'nameEn' => 'USA & Canada'],
            ['id' => '158', 'nameEn' => 'USA & Canada'],
            ['id' => '159', 'nameEn' => 'USA & Canada'],
            ['id' => '160', 'nameEn' => null],
            ['id' => '161', 'nameEn' => null],
            ['id' => '162', 'nameEn' => null],
            ['id' => '163', 'nameEn' => null],
            ['id' => '164', 'nameEn' => null],
            ['id' => '165', 'nameEn' => null],
            ['id' => '166', 'nameEn' => null],
            ['id' => '167', 'nameEn' => null],
            ['id' => '168', 'nameEn' => null],
            ['id' => '169', 'nameEn' => null],

            ['id' => '170', 'nameEn' => null],
            ['id' => '171', 'nameEn' => null],
            ['id' => '172', 'nameEn' => null],
            ['id' => '173', 'nameEn' => null],
            ['id' => '174', 'nameEn' => null],
            ['id' => '175', 'nameEn' => null],
            ['id' => '176', 'nameEn' => null],
            ['id' => '177', 'nameEn' => null],
            ['id' => '178', 'nameEn' => null],
            ['id' => '179', 'nameEn' => null],

            ['id' => '180', 'nameEn' => null],
            ['id' => '181', 'nameEn' => null],
            ['id' => '182', 'nameEn' => null],
            ['id' => '183', 'nameEn' => null],
            ['id' => '184', 'nameEn' => null],
            ['id' => '185', 'nameEn' => null],
            ['id' => '186', 'nameEn' => null],
            ['id' => '187', 'nameEn' => null],
            ['id' => '188', 'nameEn' => null],
            ['id' => '189', 'nameEn' => null],

            ['id' => '190', 'nameEn' => null],
            ['id' => '191', 'nameEn' => null],
            ['id' => '192', 'nameEn' => null],
            ['id' => '193', 'nameEn' => null],
            ['id' => '194', 'nameEn' => null],
            ['id' => '195', 'nameEn' => null],
            ['id' => '196', 'nameEn' => null],
            ['id' => '197', 'nameEn' => null],
            ['id' => '198', 'nameEn' => null],
            ['id' => '199', 'nameEn' => null],

            ['id' => '200', 'nameEn' => null],
            ['id' => '201', 'nameEn' => null],
            ['id' => '202', 'nameEn' => null],
            ['id' => '203', 'nameEn' => null],
            ['id' => '204', 'nameEn' => null],
            ['id' => '205', 'nameEn' => null],
            ['id' => '206', 'nameEn' => null],
            ['id' => '207', 'nameEn' => null],
            ['id' => '208', 'nameEn' => null],
            ['id' => '209', 'nameEn' => null],

            ['id' => '210', 'nameEn' => null],
            ['id' => '211', 'nameEn' => null],
            ['id' => '212', 'nameEn' => null],
            ['id' => '213', 'nameEn' => null],
            ['id' => '214', 'nameEn' => null],
            ['id' => '215', 'nameEn' => null],
            ['id' => '216', 'nameEn' => null],
            ['id' => '217', 'nameEn' => null],
            ['id' => '218', 'nameEn' => null],
            ['id' => '219', 'nameEn' => null],

            ['id' => '220', 'nameEn' => null],
            ['id' => '221', 'nameEn' => null],
            ['id' => '222', 'nameEn' => null],
            ['id' => '223', 'nameEn' => null],
            ['id' => '224', 'nameEn' => null],
            ['id' => '225', 'nameEn' => null],
            ['id' => '226', 'nameEn' => null],
            ['id' => '227', 'nameEn' => null],
            ['id' => '228', 'nameEn' => null],
            ['id' => '229', 'nameEn' => null],

            ['id' => '230', 'nameEn' => null],
            ['id' => '231', 'nameEn' => null],
            ['id' => '232', 'nameEn' => null],
            ['id' => '233', 'nameEn' => null],
            ['id' => '234', 'nameEn' => null],
            ['id' => '235', 'nameEn' => null],
            ['id' => '236', 'nameEn' => null],
            ['id' => '237', 'nameEn' => null],
            ['id' => '238', 'nameEn' => null],
            ['id' => '239', 'nameEn' => null],

            ['id' => '240', 'nameEn' => 'Vatican City State'],
            ['id' => '241', 'nameEn' => 'Vatican City State'],
            ['id' => '242', 'nameEn' => 'Vatican City State'],
            ['id' => '243', 'nameEn' => 'Vatican City State'],
            ['id' => '244', 'nameEn' => 'Vatican City State'],
            ['id' => '245', 'nameEn' => 'Vatican City State'],
            ['id' => '246', 'nameEn' => 'Vatican City State'],
            ['id' => '247', 'nameEn' => 'Vatican City State'],
            ['id' => '248', 'nameEn' => 'Vatican City State'],
            ['id' => '249', 'nameEn' => 'Vatican City State'],


            ['id' => '250', 'nameEn' => 'Cuba'],
            ['id' => '251', 'nameEn' => 'Cuba'],
            ['id' => '252', 'nameEn' => 'Cuba'],
            ['id' => '253', 'nameEn' => 'Cuba'],
            ['id' => '254', 'nameEn' => 'Cuba'],
            ['id' => '255', 'nameEn' => 'Cuba'],
            ['id' => '256', 'nameEn' => 'Cuba'],
            ['id' => '257', 'nameEn' => 'Cuba'],
            ['id' => '258', 'nameEn' => 'Cuba'],
            ['id' => '259', 'nameEn' => 'Cuba'],

            ['id' => '260', 'nameEn' => 'Romania'],
            ['id' => '261', 'nameEn' => 'Romania'],
            ['id' => '262', 'nameEn' => 'Romania'],
            ['id' => '263', 'nameEn' => 'Romania'],
            ['id' => '264', 'nameEn' => 'Romania'],
            ['id' => '265', 'nameEn' => 'Romania'],
            ['id' => '266', 'nameEn' => 'Romania'],
            ['id' => '267', 'nameEn' => 'Romania'],
            ['id' => '268', 'nameEn' => 'Romania'],
            ['id' => '269', 'nameEn' => 'Romania'],

            ['id' => '270', 'nameEn' => null],
            ['id' => '271', 'nameEn' => null],
            ['id' => '272', 'nameEn' => null],
            ['id' => '273', 'nameEn' => null],
            ['id' => '274', 'nameEn' => null],
            ['id' => '275', 'nameEn' => null],
            ['id' => '276', 'nameEn' => null],
            ['id' => '277', 'nameEn' => null],
            ['id' => '278', 'nameEn' => null],
            ['id' => '279', 'nameEn' => null],

            ['id' => '280', 'nameEn' => null],
            ['id' => '281', 'nameEn' => null],
            ['id' => '282', 'nameEn' => null],
            ['id' => '283', 'nameEn' => null],
            ['id' => '284', 'nameEn' => null],
            ['id' => '285', 'nameEn' => null],
            ['id' => '286', 'nameEn' => null],
            ['id' => '287', 'nameEn' => null],
            ['id' => '288', 'nameEn' => null],
            ['id' => '289', 'nameEn' => null],

            ['id' => '290', 'nameEn' => null],
            ['id' => '291', 'nameEn' => null],
            ['id' => '292', 'nameEn' => null],
            ['id' => '293', 'nameEn' => null],
            ['id' => '294', 'nameEn' => null],
            ['id' => '295', 'nameEn' => null],
            ['id' => '296', 'nameEn' => null],
            ['id' => '297', 'nameEn' => null],
            ['id' => '298', 'nameEn' => null],
            ['id' => '299', 'nameEn' => null],

            ['id' => '300', 'nameEn' => 'France'],
            ['id' => '301', 'nameEn' => 'France'],
            ['id' => '302', 'nameEn' => 'France'],
            ['id' => '303', 'nameEn' => 'France'],
            ['id' => '304', 'nameEn' => 'France'],
            ['id' => '305', 'nameEn' => 'France'],
            ['id' => '306', 'nameEn' => 'France'],
            ['id' => '307', 'nameEn' => 'France'],
            ['id' => '308', 'nameEn' => 'France'],
            ['id' => '309', 'nameEn' => 'France'],
            ['id' => '310', 'nameEn' => 'France'],
            ['id' => '311', 'nameEn' => 'France'],
            ['id' => '312', 'nameEn' => 'France'],
            ['id' => '313', 'nameEn' => 'France'],
            ['id' => '314', 'nameEn' => 'France'],
            ['id' => '315', 'nameEn' => 'France'],
            ['id' => '316', 'nameEn' => 'France'],
            ['id' => '317', 'nameEn' => 'France'],
            ['id' => '318', 'nameEn' => 'France'],
            ['id' => '319', 'nameEn' => 'France'],

            ['id' => '320', 'nameEn' => null],
            ['id' => '321', 'nameEn' => null],
            ['id' => '322', 'nameEn' => null],
            ['id' => '323', 'nameEn' => null],
            ['id' => '324', 'nameEn' => null],
            ['id' => '325', 'nameEn' => null],
            ['id' => '326', 'nameEn' => null],
            ['id' => '327', 'nameEn' => null],
            ['id' => '328', 'nameEn' => null],
            ['id' => '329', 'nameEn' => null],

            ['id' => '330', 'nameEn' => null],
            ['id' => '331', 'nameEn' => null],
            ['id' => '332', 'nameEn' => null],
            ['id' => '333', 'nameEn' => null],
            ['id' => '334', 'nameEn' => null],
            ['id' => '335', 'nameEn' => null],
            ['id' => '336', 'nameEn' => null],
            ['id' => '337', 'nameEn' => null],
            ['id' => '338', 'nameEn' => null],
            ['id' => '339', 'nameEn' => null],

            ['id' => '340', 'nameEn' => null],
            ['id' => '341', 'nameEn' => null],
            ['id' => '342', 'nameEn' => null],
            ['id' => '343', 'nameEn' => null],
            ['id' => '344', 'nameEn' => null],
            ['id' => '345', 'nameEn' => null],
            ['id' => '346', 'nameEn' => null],
            ['id' => '347', 'nameEn' => null],
            ['id' => '348', 'nameEn' => null],
            ['id' => '349', 'nameEn' => null],

            ['id' => '350', 'nameEn' => null],
            ['id' => '351', 'nameEn' => null],
            ['id' => '352', 'nameEn' => null],
            ['id' => '353', 'nameEn' => null],
            ['id' => '354', 'nameEn' => null],
            ['id' => '355', 'nameEn' => null],
            ['id' => '356', 'nameEn' => null],
            ['id' => '357', 'nameEn' => null],
            ['id' => '358', 'nameEn' => null],
            ['id' => '359', 'nameEn' => null],

            ['id' => '360', 'nameEn' => null],
            ['id' => '361', 'nameEn' => null],
            ['id' => '362', 'nameEn' => null],
            ['id' => '363', 'nameEn' => null],
            ['id' => '364', 'nameEn' => null],
            ['id' => '365', 'nameEn' => null],
            ['id' => '366', 'nameEn' => null],
            ['id' => '367', 'nameEn' => null],
            ['id' => '368', 'nameEn' => null],
            ['id' => '369', 'nameEn' => null],

            ['id' => '370', 'nameEn' => null],
            ['id' => '371', 'nameEn' => null],
            ['id' => '372', 'nameEn' => null],
            ['id' => '373', 'nameEn' => null],
            ['id' => '374', 'nameEn' => null],
            ['id' => '375', 'nameEn' => null],
            ['id' => '376', 'nameEn' => null],
            ['id' => '377', 'nameEn' => null],
            ['id' => '378', 'nameEn' => null],
            ['id' => '379', 'nameEn' => null],

            ['id' => '380', 'nameEn' => 'Bulgaria'],
            ['id' => '381', 'nameEn' => 'Bulgaria'],
            ['id' => '382', 'nameEn' => 'Bulgaria'],
            ['id' => '383', 'nameEn' => 'Bulgaria'],
            ['id' => '384', 'nameEn' => 'Bulgaria'],
            ['id' => '385', 'nameEn' => 'Bulgaria'],
            ['id' => '386', 'nameEn' => 'Bulgaria'],
            ['id' => '387', 'nameEn' => 'Bulgaria'],
            ['id' => '388', 'nameEn' => 'Bulgaria'],
            ['id' => '389', 'nameEn' => 'Bulgaria'],

            ['id' => '390', 'nameEn' => null],
            ['id' => '391', 'nameEn' => null],
            ['id' => '392', 'nameEn' => null],
            ['id' => '393', 'nameEn' => null],
            ['id' => '394', 'nameEn' => null],
            ['id' => '395', 'nameEn' => null],
            ['id' => '396', 'nameEn' => null],
            ['id' => '397', 'nameEn' => null],
            ['id' => '398', 'nameEn' => null],
            ['id' => '399', 'nameEn' => null],

            ['id' => '400', 'nameEn' => null],
            ['id' => '401', 'nameEn' => null],
            ['id' => '402', 'nameEn' => null],
            ['id' => '403', 'nameEn' => null],
            ['id' => '404', 'nameEn' => null],
            ['id' => '405', 'nameEn' => null],
            ['id' => '406', 'nameEn' => null],
            ['id' => '407', 'nameEn' => null],

            ['id' => '408', 'nameEn' => null],
            ['id' => '409', 'nameEn' => null],

            ['id' => '410', 'nameEn' => 'Germany'],
            ['id' => '411', 'nameEn' => 'Germany'],
            ['id' => '412', 'nameEn' => 'Germany'],
            ['id' => '413', 'nameEn' => 'Germany'],
            ['id' => '414', 'nameEn' => 'Germany'],
            ['id' => '415', 'nameEn' => 'Germany'],
            ['id' => '416', 'nameEn' => 'Germany'],
            ['id' => '417', 'nameEn' => 'Germany'],
            ['id' => '418', 'nameEn' => 'Germany'],
            ['id' => '419', 'nameEn' => 'Germany'],

            ['id' => '420', 'nameEn' => null],
            ['id' => '421', 'nameEn' => null],
            ['id' => '422', 'nameEn' => null],
            ['id' => '423', 'nameEn' => null],
            ['id' => '424', 'nameEn' => null],
            ['id' => '425', 'nameEn' => null],
            ['id' => '426', 'nameEn' => null],
            ['id' => '427', 'nameEn' => null],
            ['id' => '428', 'nameEn' => null],
            ['id' => '429', 'nameEn' => null],

            ['id' => '430', 'nameEn' => null],
            ['id' => '431', 'nameEn' => null],
            ['id' => '432', 'nameEn' => null],
            ['id' => '433', 'nameEn' => null],
            ['id' => '434', 'nameEn' => null],
            ['id' => '435', 'nameEn' => null],
            ['id' => '436', 'nameEn' => null],
            ['id' => '437', 'nameEn' => null],
            ['id' => '438', 'nameEn' => null],
            ['id' => '439', 'nameEn' => null],

            ['id' => '440', 'nameEn' => null],
            ['id' => '441', 'nameEn' => null],
            ['id' => '442', 'nameEn' => null],
            ['id' => '443', 'nameEn' => null],
            ['id' => '444', 'nameEn' => null],
            ['id' => '445', 'nameEn' => null],
            ['id' => '446', 'nameEn' => null],
            ['id' => '447', 'nameEn' => null],
            ['id' => '448', 'nameEn' => null],
            ['id' => '449', 'nameEn' => null],

            ['id' => '450', 'nameEn' => 'Japan'],
            ['id' => '451', 'nameEn' => 'Japan'],
            ['id' => '452', 'nameEn' => 'Japan'],
            ['id' => '453', 'nameEn' => 'Japan'],
            ['id' => '454', 'nameEn' => 'Japan'],
            ['id' => '455', 'nameEn' => 'Japan'],
            ['id' => '456', 'nameEn' => 'Japan'],
            ['id' => '457', 'nameEn' => 'Japan'],
            ['id' => '458', 'nameEn' => 'Japan'],
            ['id' => '459', 'nameEn' => 'Japan'],
            ['id' => '460', 'nameEn' => 'Russia'],
            ['id' => '461', 'nameEn' => 'Russia'],
            ['id' => '462', 'nameEn' => 'Russia'],
            ['id' => '463', 'nameEn' => 'Russia'],
            ['id' => '464', 'nameEn' => 'Russia'],
            ['id' => '465', 'nameEn' => 'Russia'],
            ['id' => '466', 'nameEn' => 'Russia'],
            ['id' => '467', 'nameEn' => 'Russia'],
            ['id' => '468', 'nameEn' => 'Russia'],
            // ...
            ['id' => '469', 'nameEn' => 'Russia'],

            ['id' => '470', 'nameEn' => 'Kyrgyzstan'],
            ['id' => '471', 'nameEn' => 'Taiwan'],
            ['id' => '474', 'nameEn' => 'Estonia'],
            ['id' => '475', 'nameEn' => 'Latvia'],
            ['id' => '476', 'nameEn' => 'Azerbaijan'],
            ['id' => '477', 'nameEn' => 'Lithuania'],
            ['id' => '478', 'nameEn' => 'Uzbekistan'],
            ['id' => '479', 'nameEn' => 'Sri Lanka'],
            ['id' => '480', 'nameEn' => 'Philippines'],
            ['id' => '481', 'nameEn' => 'Belarus'],
            ['id' => '482', 'nameEn' => 'Ukraine'],
            ['id' => '483', 'nameEn' => 'Turkmenistan'],
            ['id' => '484', 'nameEn' => 'Moldova'],
            ['id' => '485', 'nameEn' => 'Armenia'],
            ['id' => '486', 'nameEn' => 'Georgia'],
            ['id' => '487', 'nameEn' => 'Kazakhstan'],
            ['id' => '488', 'nameEn' => 'Tajikistan'],
            ['id' => '489', 'nameEn' => 'Hong Kong'],
            ['id' => '490', 'nameEn' => 'Japan'],
            ['id' => '491', 'nameEn' => 'Japan'],
            ['id' => '492', 'nameEn' => 'Japan'],
            ['id' => '493', 'nameEn' => 'Japan'],
            ['id' => '494', 'nameEn' => 'Japan'],
            ['id' => '495', 'nameEn' => 'Japan'],
            ['id' => '496', 'nameEn' => 'Japan'],
            ['id' => '497', 'nameEn' => 'Japan'],
            ['id' => '498', 'nameEn' => 'Japan'],
            ['id' => '499', 'nameEn' => 'Japan'],

            ['id' => '500', 'nameEn' => 'UK'],
            ['id' => '501', 'nameEn' => 'UK'],
            ['id' => '502', 'nameEn' => 'UK'],
            ['id' => '503', 'nameEn' => 'UK'],
            ['id' => '504', 'nameEn' => 'UK'],
            ['id' => '505', 'nameEn' => 'UK'],
            ['id' => '506', 'nameEn' => 'UK'],
            ['id' => '507', 'nameEn' => 'UK'],
            ['id' => '508', 'nameEn' => 'UK'],
            ['id' => '509', 'nameEn' => 'UK'],
            ['id' => '520', 'nameEn' => 'Greece'],
            ['id' => '521', 'nameEn' => 'Greece'],
            ['id' => '522', 'nameEn' => 'Greece'],
            ['id' => '523', 'nameEn' => 'Greece'],
            ['id' => '524', 'nameEn' => 'Greece'],
            ['id' => '525', 'nameEn' => 'Greece'],
            ['id' => '526', 'nameEn' => 'Greece'],
            ['id' => '527', 'nameEn' => 'Greece'],
            ['id' => '528', 'nameEn' => 'Greece'],
            ['id' => '529', 'nameEn' => 'Greece'],

            ['id' => '530', 'nameEn' => 'Albania'],
            ['id' => '531', 'nameEn' => 'Macedonia'],
            ['id' => '532', 'nameEn' => 'Malta'],
            ['id' => '533', 'nameEn' => 'Cyprus'],
            ['id' => '534', 'nameEn' => null],
            ['id' => '535', 'nameEn' => null],
            ['id' => '536', 'nameEn' => null],
            ['id' => '537', 'nameEn' => null],
            ['id' => '538', 'nameEn' => null],
            ['id' => '539', 'nameEn' => null],

            ['id' => '540', 'nameEn' => null],
            ['id' => '541', 'nameEn' => null],
            ['id' => '542', 'nameEn' => null],
            ['id' => '543', 'nameEn' => null],
            ['id' => '544', 'nameEn' => null],
            ['id' => '545', 'nameEn' => null],
            ['id' => '546', 'nameEn' => null],
            ['id' => '547', 'nameEn' => null],
            ['id' => '548', 'nameEn' => null],
            ['id' => '549', 'nameEn' => null],

            ['id' => '560',  'nameEn' => 'Portugal'],
            ['id' => '561',  'nameEn' => 'Portugal'],
            ['id' => '562',  'nameEn' => 'Portugal'],
            ['id' => '563',  'nameEn' => 'Portugal'],
            ['id' => '564',  'nameEn' => 'Portugal'],
            ['id' => '565',  'nameEn' => 'Portugal'],
            ['id' => '566',  'nameEn' => 'Portugal'],
            ['id' => '567',  'nameEn' => 'Portugal'],
            ['id' => '568',  'nameEn' => 'Portugal'],
            ['id' => '569',  'nameEn' => 'Portugal'],
            ['id' => '570', 'nameEn' => 'Denmark'],
            ['id' => '571', 'nameEn' => 'Denmark'],
            ['id' => '572', 'nameEn' => 'Denmark'],
            ['id' => '573', 'nameEn' => 'Denmark'],
            ['id' => '574', 'nameEn' => 'Denmark'],
            ['id' => '575', 'nameEn' => 'Denmark'],
            ['id' => '576', 'nameEn' => 'Denmark'],
            ['id' => '577', 'nameEn' => 'Denmark'],
            ['id' => '578', 'nameEn' => 'Denmark'],
            ['id' => '579', 'nameEn' => 'Denmark'],

            ['id' => '580', 'nameEn' => null],
            ['id' => '581', 'nameEn' => null],
            ['id' => '582', 'nameEn' => null],
            ['id' => '583', 'nameEn' => null],
            ['id' => '584', 'nameEn' => null],
            ['id' => '585', 'nameEn' => null],
            ['id' => '586', 'nameEn' => null],
            ['id' => '587', 'nameEn' => null],
            ['id' => '588', 'nameEn' => null],
            ['id' => '589', 'nameEn' => null],
            ['id' => '590', 'nameEn' => 'Poland'],
            ['id' => '591', 'nameEn' => 'Poland'],
            ['id' => '592', 'nameEn' => 'Poland'],
            ['id' => '593', 'nameEn' => 'Poland'],
            ['id' => '594', 'nameEn' => 'Poland'],
            ['id' => '595', 'nameEn' => 'Poland'],
            ['id' => '596', 'nameEn' => 'Poland'],
            ['id' => '597', 'nameEn' => 'Poland'],
            ['id' => '598', 'nameEn' => 'Poland'],
            ['id' => '599', 'nameEn' => 'Poland'],

            ['id' => '600', 'nameEn' => null],
            ['id' => '601', 'nameEn' => null],
            ['id' => '602', 'nameEn' => null],
            ['id' => '603', 'nameEn' => null],
            ['id' => '604', 'nameEn' => null],
            ['id' => '605', 'nameEn' => null],
            ['id' => '606', 'nameEn' => null],
            ['id' => '607', 'nameEn' => null],
            ['id' => '608', 'nameEn' => null],
            ['id' => '609', 'nameEn' => null],

            ['id' => '610', 'nameEn' => null],
            ['id' => '611', 'nameEn' => null],
            ['id' => '612', 'nameEn' => null],
            ['id' => '613', 'nameEn' => null],
            ['id' => '614', 'nameEn' => null],
            ['id' => '615', 'nameEn' => null],
            ['id' => '616', 'nameEn' => null],
            ['id' => '617', 'nameEn' => null],
            ['id' => '618', 'nameEn' => null],
            ['id' => '619', 'nameEn' => null],

            ['id' => '620',  'nameEn' => null],
            ['id' => '621',  'nameEn' => null],
            ['id' => '622',  'nameEn' => null],
            ['id' => '623',  'nameEn' => null],
            ['id' => '624',  'nameEn' => null],
            ['id' => '625',  'nameEn' => null],
            ['id' => '626',  'nameEn' => null],
            ['id' => '627',  'nameEn' => null],
            ['id' => '628',  'nameEn' => null],
            ['id' => '629',  'nameEn' => null],

            ['id' => '630', 'nameEn' => 'Egypt'],
            ['id' => '631', 'nameEn' => 'Egypt'],
            ['id' => '632', 'nameEn' => 'Egypt'],
            ['id' => '633', 'nameEn' => 'Egypt'],
            ['id' => '634', 'nameEn' => 'Egypt'],
            ['id' => '635', 'nameEn' => 'Egypt'],
            ['id' => '636', 'nameEn' => 'Egypt'],
            ['id' => '637', 'nameEn' => 'Egypt'],
            ['id' => '638', 'nameEn' => 'Egypt'],
            ['id' => '639', 'nameEn' => 'Egypt'],

            ['id' => '640', 'nameEn' => null],
            ['id' => '641', 'nameEn' => null],
            ['id' => '642', 'nameEn' => null],
            ['id' => '643', 'nameEn' => null],
            ['id' => '644', 'nameEn' => null],
            ['id' => '645', 'nameEn' => null],
            ['id' => '646', 'nameEn' => null],
            ['id' => '647', 'nameEn' => null],
            ['id' => '648', 'nameEn' => null],
            ['id' => '649', 'nameEn' => null],

            ['id' => '650',  'nameEn' => 'Finland'],
            ['id' => '651',  'nameEn' => 'Finland'],
            ['id' => '652',  'nameEn' => 'Finland'],
            ['id' => '653',  'nameEn' => 'Finland'],
            ['id' => '654',  'nameEn' => 'Finland'],
            ['id' => '655',  'nameEn' => 'Finland'],
            ['id' => '656',  'nameEn' => 'Finland'],
            ['id' => '657',  'nameEn' => 'Finland'],
            ['id' => '658',  'nameEn' => 'Finland'],
            ['id' => '659',  'nameEn' => 'Finland'],

            ['id' => '660', 'nameEn' => null],
            ['id' => '661', 'nameEn' => null],
            ['id' => '690', 'nameEn' => 'China'],
            ['id' => '691', 'nameEn' => 'China'],
            ['id' => '692', 'nameEn' => 'China'],
            ['id' => '693', 'nameEn' => 'China'],
            ['id' => '694', 'nameEn' => 'China'],
            ['id' => '695', 'nameEn' => 'China'],
            ['id' => '696', 'nameEn' => 'China'],
            ['id' => '697', 'nameEn' => 'China'],
            ['id' => '698', 'nameEn' => 'China'],

            ['id' => '699', 'nameEn' => 'China'],
            ['id' => '700', 'nameEn' => 'Norway'],
            ['id' => '701', 'nameEn' => 'Norway'],
            ['id' => '702', 'nameEn' => 'Norway'],
            ['id' => '703', 'nameEn' => 'Norway'],
            ['id' => '704', 'nameEn' => 'Norway'],
            ['id' => '705', 'nameEn' => 'Norway'],
            ['id' => '706', 'nameEn' => 'Norway'],
            ['id' => '707', 'nameEn' => 'Norway'],
            ['id' => '708', 'nameEn' => 'Norway'],
            ['id' => '709', 'nameEn' => 'Norway'],

            ['id' => '710', 'nameEn' => 'Colombia'],
            ['id' => '711', 'nameEn' => 'Colombia'],
            ['id' => '712', 'nameEn' => 'Colombia'],
            ['id' => '713', 'nameEn' => 'Colombia'],
            ['id' => '714', 'nameEn' => 'Colombia'],
            ['id' => '715', 'nameEn' => 'Colombia'],
            ['id' => '716', 'nameEn' => 'Colombia'],
            ['id' => '717', 'nameEn' => 'Colombia'],
            ['id' => '718', 'nameEn' => 'Colombia'],
            ['id' => '719', 'nameEn' => 'Colombia'],

            ['id' => '720',  'nameEn' => null],
            ['id' => '721',  'nameEn' => null],
            ['id' => '722',  'nameEn' => null],
            ['id' => '723',  'nameEn' => null],
            ['id' => '724',  'nameEn' => null],
            ['id' => '725',  'nameEn' => null],
            ['id' => '726',  'nameEn' => null],
            ['id' => '727',  'nameEn' => null],
            ['id' => '728',  'nameEn' => null],


            ['id' => '729', 'nameEn' => 'Israel'],
            ['id' => '730', 'nameEn' => 'Chile'],
            ['id' => '731', 'nameEn' => 'Chile'],
            ['id' => '732', 'nameEn' => 'Chile'],
            ['id' => '733', 'nameEn' => 'Chile'],
            ['id' => '734', 'nameEn' => 'Chile'],
            ['id' => '735', 'nameEn' => 'Chile'],
            ['id' => '736', 'nameEn' => 'Chile'],
            ['id' => '737', 'nameEn' => 'Chile'],
            ['id' => '738', 'nameEn' => 'Chile'],
            ['id' => '739', 'nameEn' => 'Chile'],

            ['id' => '740', 'nameEn' => 'Guatemala'],
            ['id' => '741', 'nameEn' => 'El Salvador'],
            ['id' => '742', 'nameEn' => 'Honduras'],
            ['id' => '743', 'nameEn' => 'Nicaragua'],
            ['id' => '744', 'nameEn' => 'Costa Rica'],
            ['id' => '745', 'nameEn' => null],
            ['id' => '746', 'nameEn' => null],
            ['id' => '747', 'nameEn' => null],
            ['id' => '748', 'nameEn' => null],
            ['id' => '749', 'nameEn' => null],

            ['id' => '750', 'nameEn' => 'Mexico'],
            ['id' => '751', 'nameEn' => 'Mexico'],
            ['id' => '752', 'nameEn' => 'Mexico'],
            ['id' => '753', 'nameEn' => 'Mexico'],
            ['id' => '754', 'nameEn' => 'Mexico'],
            ['id' => '755', 'nameEn' => 'Mexico'],
            ['id' => '756', 'nameEn' => 'Mexico'],
            ['id' => '757', 'nameEn' => 'Mexico'],
            ['id' => '758', 'nameEn' => 'Mexico'],
            ['id' => '759', 'nameEn' => 'Mexico'],

            ['id' => '760',  'nameEn' => 'Switzerland'],
            ['id' => '761',  'nameEn' => 'Switzerland'],
            ['id' => '762',  'nameEn' => 'Switzerland'],
            ['id' => '763',  'nameEn' => 'Switzerland'],
            ['id' => '764',  'nameEn' => 'Switzerland'],
            ['id' => '765',  'nameEn' => 'Switzerland'],
            ['id' => '766',  'nameEn' => 'Switzerland'],
            ['id' => '767',  'nameEn' => 'Switzerland'],
            ['id' => '768',  'nameEn' => 'Switzerland'],
            ['id' => '769',  'nameEn' => 'Switzerland'],

            ['id' => '770',  'nameEn' => null],
            ['id' => '771',  'nameEn' => null],
            ['id' => '772',  'nameEn' => null],
            ['id' => '773',  'nameEn' => null],
            ['id' => '774',  'nameEn' => null],
            ['id' => '775',  'nameEn' => null],
            ['id' => '776',  'nameEn' => null],
            ['id' => '777',  'nameEn' => null],
            ['id' => '778',  'nameEn' => null],
            ['id' => '779',  'nameEn' => null],

            ['id' => '780',  'nameEn' => 'Colombia'],
            ['id' => '781',  'nameEn' => 'Colombia'],
            ['id' => '782',  'nameEn' => 'Colombia'],
            ['id' => '783',  'nameEn' => 'Colombia'],
            ['id' => '784',  'nameEn' => 'Colombia'],
            ['id' => '785',  'nameEn' => 'Colombia'],
            ['id' => '786',  'nameEn' => 'Colombia'],
            ['id' => '787',  'nameEn' => 'Puerto Rico'],
            ['id' => '788',  'nameEn' => 'Puerto Rico'],

            ['id' => '789', 'nameEn' => 'Brazil'],
            ['id' => '790', 'nameEn' => 'Brazil'],
            ['id' => '791', 'nameEn' => 'Brazil'],
            ['id' => '792', 'nameEn' => 'Brazil'],
            ['id' => '793', 'nameEn' => 'Brazil'],
            ['id' => '794', 'nameEn' => 'Brazil'],
            ['id' => '795', 'nameEn' => 'Brazil'],
            ['id' => '796', 'nameEn' => 'Brazil'],
            ['id' => '797', 'nameEn' => 'Brazil'],
            ['id' => '798', 'nameEn' => 'Brazil'],


            ['id' => '800', 'nameEn' => 'Italy'],
            // ...
            ['id' => '839', 'nameEn' => 'Italy'],

            ['id' => '840', 'nameEn' => 'Spain'],
            // ...
            ['id' => '849', 'nameEn' => 'Spain'],
            ['id' => '850', 'nameEn' => 'Cuba'],
            ['id' => '858', 'nameEn' => 'Slovakia'],
            ['id' => '859', 'nameEn' => 'Czech Republic'],
            ['id' => '860', 'nameEn' => 'Serbia'],
            ['id' => '861', 'nameEn' => 'Mongolia'],
            ['id' => '862', 'nameEn' => 'Morocco'],
            ['id' => '863', 'nameEn' => 'Côte d\'Ivoire'],
            ['id' => '864', 'nameEn' => 'Syria'],
            ['id' => '865', 'nameEn' => 'Mongolia'],
            ['id' => '866', 'nameEn' => 'North Korea'],
            ['id' => '867', 'nameEn' => 'Bangladesh'],
            ['id' => '868', 'nameEn' => 'Türkiye'],
            ['id' => '869', 'nameEn' => 'Türkiye'],

            ['id' => '870', 'nameEn' => 'Netherlands'],
            ['id' => '871', 'nameEn' => 'Netherlands'],
            ['id' => '872', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '873', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '874', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '875', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '876', 'nameEn' => 'Saint Pierre and Miquelon'],
            ['id' => '877', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '878', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '879', 'nameEn' => 'Netherlands Antilles'],
            ['id' => '880', 'nameEn' => 'South Korea'],
            ['id' => '881', 'nameEn' => 'South Korea'],
            ['id' => '882', 'nameEn' => 'South Korea'],
            ['id' => '883', 'nameEn' => 'South Korea'],
            ['id' => '884', 'nameEn' => 'Cambodia'],
            ['id' => '885', 'nameEn' => 'Thailand'],
            ['id' => '886', 'nameEn' => 'Taiwan'],
            ['id' => '887', 'nameEn' => 'Bangladesh'],
            ['id' => '888', 'nameEn' => 'Singapore'],
            ['id' => '889', 'nameEn' => 'Singapore'],


            ['id' => '890', 'nameEn' => 'India'],
            ['id' => '891', 'nameEn' => 'India'],
            ['id' => '892', 'nameEn' => 'India'],
            ['id' => '893', 'nameEn' => 'India'],
            ['id' => '894', 'nameEn' => 'India'],
            ['id' => '895', 'nameEn' => 'India'],
            ['id' => '896', 'nameEn' => 'India'],
            ['id' => '897', 'nameEn' => 'India'],
            ['id' => '898', 'nameEn' => 'India'],
            ['id' => '899', 'nameEn' => 'India'],

            ['id' => '900', 'nameEn' => 'Austria'],
            // ...
            ['id' => '919', 'nameEn' => 'Austria'],

            ['id' => '920', 'nameEn' => 'Serbia'],
            ['id' => '921', 'nameEn' => 'Bosnia and Herzegovina'],
            ['id' => '922', 'nameEn' => 'Montenegro'],
            ['id' => '923', 'nameEn' => 'Slovenia'],
            ['id' => '924', 'nameEn' => 'Croatia'],
            ['id' => '925', 'nameEn' => 'Republic of North Macedonia'],
            ['id' => '926', 'nameEn' => 'Albania'],
            ['id' => '927', 'nameEn' => 'Malta'],
            ['id' => '928', 'nameEn' => null],
            ['id' => '929', 'nameEn' => null],

            ['id' => '930', 'nameEn' => 'Australia'],
            ['id' => '931', 'nameEn' => 'Australia'],
            ['id' => '932', 'nameEn' => 'Australia'],
            ['id' => '933', 'nameEn' => 'Australia'],
            ['id' => '934', 'nameEn' => 'Australia'],
            ['id' => '935', 'nameEn' => 'Australia'],
            ['id' => '936', 'nameEn' => 'Australia'],
            ['id' => '937', 'nameEn' => 'Australia'],
            ['id' => '938', 'nameEn' => 'Australia'],
            // ...
            ['id' => '939', 'nameEn' => 'Australia'],

            ['id' => '940', 'nameEn' => 'New Zealand'],
            ['id' => '941', 'nameEn' => 'New Zealand'],
            ['id' => '942', 'nameEn' => 'New Zealand'],
            ['id' => '943', 'nameEn' => 'New Zealand'],
            ['id' => '944', 'nameEn' => 'New Zealand'],
            ['id' => '945', 'nameEn' => 'New Zealand'],
            ['id' => '946', 'nameEn' => 'New Zealand'],
            ['id' => '947', 'nameEn' => 'New Zealand'],
            ['id' => '948', 'nameEn' => 'New Zealand'],
            // ...
            ['id' => '949', 'nameEn' => 'New Zealand'],

            ['id' => '950', 'nameEn' => 'Global Office Use'],
            ['id' => '951', 'nameEn' => 'Global Office Use'],
            ['id' => '952', 'nameEn' => 'Global Office Use'],
            ['id' => '953', 'nameEn' => 'Global Office Use'],
            ['id' => '954', 'nameEn' => 'Global Office Use'],


            ['id' => '955', 'nameEn' => 'Malaysia'],
            ['id' => '956', 'nameEn' => 'Malaysia'],
            ['id' => '957', 'nameEn' => 'Malaysia'],

            ['id' => '958', 'nameEn' => 'Macau'],
            ['id' => '959', 'nameEn' => 'Macau'],

            ['id' => '960', 'nameEn' => 'GS1 US'],
            ['id' => '961', 'nameEn' => 'GS1 US'],
            ['id' => '962', 'nameEn' => 'GS1 US'],
            ['id' => '963', 'nameEn' => 'GS1 US'],
            ['id' => '964', 'nameEn' => 'GS1 US'],
            ['id' => '965', 'nameEn' => 'GS1 US'],
            ['id' => '966', 'nameEn' => 'GS1 US'],
            ['id' => '967', 'nameEn' => 'GS1 US'],
            ['id' => '968', 'nameEn' => 'GS1 US'],
            ['id' => '969', 'nameEn' => 'GS1 US'],

            ['id' => '970',  'nameEn' => null],
            ['id' => '971',  'nameEn' => null],
            ['id' => '972',  'nameEn' => null],
            ['id' => '973',  'nameEn' => null],
            ['id' => '974',  'nameEn' => null],
            ['id' => '975',  'nameEn' => null],
            ['id' => '976',  'nameEn' => null],
            ['id' => '977',  'nameEn' => null],
            ['id' => '978',  'nameEn' => null],
            ['id' => '979',  'nameEn' => null],

            ['id' => '980',  'nameEn' => null],
            ['id' => '981',  'nameEn' => null],
            ['id' => '982',  'nameEn' => null],
            ['id' => '983',  'nameEn' => null],
            ['id' => '984',  'nameEn' => null],
            ['id' => '985',  'nameEn' => null],
            ['id' => '986',  'nameEn' => null],
            ['id' => '987',  'nameEn' => null],
            ['id' => '988',  'nameEn' => null],
            ['id' => '989',  'nameEn' => null],

            ['id' => '990', 'nameEn' => 'Coupons'],
            ['id' => '991', 'nameEn' => 'Coupons'],
            ['id' => '992', 'nameEn' => 'Coupons'],
            ['id' => '993', 'nameEn' => 'Coupons'],
            ['id' => '994', 'nameEn' => 'Coupons'],
            ['id' => '995', 'nameEn' => 'Coupons'],
            ['id' => '996', 'nameEn' => 'Coupons'],
            ['id' => '997', 'nameEn' => 'Coupons'],
            ['id' => '998', 'nameEn' => 'Coupons'],
            ['id' => '999', 'nameEn' => 'Coupons'],
        ];

        foreach ($data as $row) {
            Gtin::updateOrCreate(['id' => $row['id']], $row);
        }
    }
}
